### ISSUE TITLE
I can't build the code

### ISSUE THREAD

**Issue by WangFengtu1996** [rsasaki0109/littleslam_ros2#1]
Starting >>> littleslam_ros2
--- stderr: littleslam_ros2
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCL" (requested
  version 1.8) with any of the following names:

    PCLConfig.cmake
    pcl-config.cmake

  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.

---
Failed   <<< littleslam_ros2    [ Exited with code 1 ]

Summary: 0 packages finished [15.1s]
  1 package failed: littleslam_ros2
  1 package had stderr output: littleslam_ros2

thanks for your time.

**Comment by rsasaki0109** [comment]
Is a PCL installed in your PC?

In ubuntu, You can install it in the following way.

```
sudo apt install libpcl-dev

```

And, I didn't add a dependency about a PCL in package.xml, so I did it.
You can also install it by rosdep.
https://github.com/rsasaki0109/littleslam_ros2/blob/master/package.xml#L15
