### ISSUE TITLE
Nothing showing up on rviz2?

### ISSUE THREAD

**Issue by OforiDarren** [rsasaki0109/littleslam_ros2#2]
Hello, 
I followed the steps but is it not the purpose of this package to be able to make a map with the lidar? After every step it is indeed running without errors but I dont't know what to expect since it doesn't show anything on the rviz2 program when I run it as well .

**Comment by rsasaki0109** [comment]
I'm sorry, I didn't notice your issue. With the demo data, you can visualize the map using `rviz2 -d config/demo.rviz`. Please let me know if you encounter any further problems.
